### ISSUE TITLE
puteau fi 2 filtre aici fara probleme in loc de &&

### ISSUE THREAD

**Issue by stefanbulzan** [roscaioana11/full-stack-java-practice#3]
https://github.com/roscaioana11/full-stack-java-practice/blob/a0e4cc6fe02d6c8aea827ce9d7b025c2067e4390/src/main/java/ro/fasttackit/homeworks/c2homework/inheritance/PersonReportGenerator.java#L26

**Comment by roscaioana11** [comment]
Fixed
